# application-staging.yml

# 1. API PORT
server:
  port: 8080

# 2. ADATBÁZIS (Redis)
spring:
  data:
    redis:
      host: redis
      port: 6379

  # 3. BIZTONSÁG (Keycloak)
  security:
    oauth2:
      resourceserver:
        jwt:
          # A staging környezetben a Docker hálózaton belüli nevet (keycloak)
          # és a dedikált portot használunk: 9080
          issuer-uri: http://keycloak:9080/realms/student-productivity-realm